### ISSUE TITLE
Erro na criação do modelo a partir do Modelfile [ Ambiente Linux ZSH ]

### ISSUE THREAD

**Issue by henriquemarlon** [rmnicola/m8-ec-encontros#83]
% ollama create dexter -f modelfile
⠋ couldn't open modelfile '/home/henriquemarlon/Projects/ativ4-m8/modelfile'  Error: failed to open file: open /home/henriquemarlon/Projects/ativ4-m8/modelfile: permission denied

Estou recebendo esse erro quando tento criar/rodar um modelo a partir de um Modelfile.

Mesmo depois de rodar o comando para dar permissões para o usuário ollama na sessão do terminal:

`chmod -R o+rx .`

referência da docs do grande Nicola:

https://rmnicola.github.io/m8-ec-encontros/sprint3/encontro6/ollama#3-interagindo-com-o-modelfile

**Comment by rmnicola** [comment]
Problema foi resolvido [nesse PR](https://github.com/jmorganca/ollama/pull/898) do repositório do Ollama. Aguardar a release `v0.1.10` ou dar build do código fonte.
